# Generated by Django 4.2.27 on 2026-01-04 20:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('museum', 'Museum'), ('experience', 'Experience')], max_length=20)),
                ('address', models.CharField(max_length=500)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('website', models.URLField(blank=True, max_length=500, null=True)),
                ('opening_hours', models.CharField(blank=True, max_length=500, null=True)),
                ('price', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('autostrade_exit', models.CharField(blank=True, max_length=255, null=True)),
                ('distance_from_exit', models.DecimalField(blank=True, decimal_places=2, help_text='Distance from highway exit in kilometers', max_digits=6, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('museum', 'Museum'), ('experience', 'Experience')], max_length=20)),
                ('address', models.CharField(max_length=500)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('website', models.URLField(blank=True, max_length=500, null=True)),
                ('opening_hours', models.CharField(blank=True, max_length=500, null=True)),
                ('price', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('autostrade_exit', models.CharField(blank=True, max_length=255, null=True)),
                ('distance_from_exit', models.DecimalField(blank=True, decimal_places=2, help_text='Distance from highway exit in kilometers', max_digits=6, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('needs_changes', 'Needs Changes')], default='pending', max_length=20)),
                ('reviewer_notes', models.TextField(blank=True, help_text='Internal notes from reviewer', null=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason shown to submitter if rejected', null=True)),
                ('submitter_email', models.EmailField(blank=True, help_text='Optional email for notifications', max_length=254, null=True)),
                ('submitter_name', models.CharField(blank=True, max_length=255, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_attraction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='attractions.attraction')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.AddIndex(
            model_name='attraction',
            index=models.Index(fields=['type'], name='attractions_type_20442a_idx'),
        ),
        migrations.AddIndex(
            model_name='attraction',
            index=models.Index(fields=['status'], name='attractions_status_aea291_idx'),
        ),
        migrations.AddIndex(
            model_name='attraction',
            index=models.Index(fields=['autostrade_exit'], name='attractions_autostr_f96cea_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['status'], name='attractions_status_6a7b5f_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['submitted_at'], name='attractions_submitt_fd4f46_idx'),
        ),
    ]
